### Intro to NUMPY

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/vadiveld/opt/anaconda3/envs/ml-zoomcamp/lib/python3.9/site-packages/numpy/__init__.py'>

### Creating Arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,9])
a

array([1, 2, 3, 5, 7, 9])

In [7]:
a[2]

3

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [16]:
matrix[0,1]

2

In [17]:
matrix[2]

array([7, 8, 9])

In [18]:
matrix[:,2]

array([3, 6, 9])

### Randomly generated arrays

In [19]:
np.random.rand(5,3)

array([[0.18794565, 0.12518958, 0.93063048],
       [0.08305765, 0.48245642, 0.93478459],
       [0.30291427, 0.23325216, 0.08770596],
       [0.95272748, 0.73739138, 0.61617205],
       [0.94137527, 0.2030757 , 0.21079657]])

In [20]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

### Element Wise operator

In [21]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
b= (10 + (a*2)) **2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison operations

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
a > b

array([False, False,  True,  True,  True])

In [30]:
a[a>b]

array([2, 3, 4])

### Summary operations

In [31]:
a.mean()

2.0

In [32]:
a.std()

1.4142135623730951

In [33]:
matrix.mean()

5.0

In [34]:
matrix.min()

1