In [1]:
import numpy as np

### Vector operations

In [3]:
u = np.arange(2,7)
u

array([2, 3, 4, 5, 6])

In [4]:
u * 2

array([ 4,  6,  8, 10, 12])

In [10]:
v = np.array([1,0,0,1,2],dtype='float')
v

array([1., 0., 0., 1., 2.])

In [9]:
u + v

array([3, 3, 4, 6, 8])

### Multiplications

#### Vector-vector multiplication (Dot product)


In [16]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [18]:
vector_vector_multiplication(u,v)

19.0

### Matrix-vector multiplication

In [20]:
u = np.array([[2,3,4,5],
              [1,2,1,1],
              [3,1,2,1]
              ])

v = np.array([1,2,0.5,1])

In [21]:
def matrix_vector_multiplication(U,v ):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result

In [22]:
matrix_vector_multiplication(u,v)

array([15. ,  6.5,  7. ])

### Matrix-Matrix Multiplication

In [24]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [27]:
V = np.array([[1,1,2],
             [0,0.5,1],
             [0,2,1],
             [1,1,2]])

In [29]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [1. , 1. , 2. ]])

In [30]:
matrix_matrix_multiplication(u,V)

array([[ 7. , 16.5, 21. ],
       [ 2. ,  5. ,  7. ],
       [ 4. ,  8.5, 11. ]])

### Identity matrix

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])